import { defineConfig } from 'orval';

// Task 0010: Fetch-based TypeScript client generated from the backend OpenAPI
// document. Never edit anything under `src/api/generated/` by hand — rerun
// `pnpm api:generate` (or `pnpm api:check`) instead.
export default defineConfig({
  fileManager: {
    input: {
      target: './openapi/openapi.json',
    },
    output: {
      mode: 'split',
      target: 'src/api/generated/file-manager-api.ts',
      schemas: 'src/api/generated/models',
      client: 'fetch',
      override: {
        mutator: {
          path: 'src/api/fetch-mutator.ts',
          name: 'fetchMutator',
        },
        header: () => [
          'Generated by Orval from frontend/openapi/openapi.json — do not edit by hand.',
          'Run `pnpm api:generate` (or `pnpm api:check`) to regenerate.',
        ],
      },
    },
  },
});
